version: "3.8"
services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"

  db:
    image: mysql:8.0.33
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Abcd123@
      MYSQL_DATABASE: ecommerce
    ports:
      - "3307:3307"
    expose:
      - 3307
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u root -p Abcd123@ || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - db_data:/var/lib/mysql
    networks:
       - ecommerce-network
  redis:
    image: redis:7.0
    container_name: e-commerce-redis
    ports:
      - "6379:6379"
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge

volumes:
  db_data:
