services:
  app:
    image: e-commerce-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/e-commerce
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=arin980921
    depends_on:
      - db

  db:
    image: mysql:8.0.33
    environment:
      MYSQL_ROOT_PASSWORD: arin980921
      MYSQL_DATABASE: e-commerce
    ports:
      - "3307:3306"
    volumes:
      - ./data:/var/lib/mysql  # 호스트와 컨테이너 간의 데이터 공유
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # 초기화 스크립트


volumes:
  db_data:
